services:
  - type: web
    name: portfolio-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.portfolio_agent_backend:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OLLAMA_BASE_URL
        value: http://ollama:11434
      - key: EMBEDDING_MODEL
        value: nomic-embed-text
      - key: LLM_MODEL
        value: tinyllama
    plan: standard
    resources:
      memory: 1GB
      cpu: 1 